# Generated by Django 4.2.11 on 2024-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manger_UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Manager_username", models.CharField(max_length=32)),
                ("Manager_password", models.CharField(max_length=20)),
            ],
        ),
    ]
