# Generated by Django 4.2.11 on 2024-03-20 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manger_UserInfo",
            new_name="Manager_UserInfo",
        ),
    ]
