# Generated by Django 4.2.11 on 2024-03-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_rename_manger_userinfo_manager_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager_userinfo",
            name="Manager_age",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="manager_userinfo",
            name="Manager_email",
            field=models.EmailField(default="<123@gmail.com>", max_length=254),
        ),
    ]
